baseURL = "https://luismacorral.github.io/blogcv/"
languageCode = "es"
title = "Mi blog CV"
theme ="tale"

[menu]
  [[menu.main]]
	identifier = "c#"
	name = "C#"
	title = "c#"
	url = "/csharp/"
	weight = 0
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 0